name: Gapples
version: 0.3
main: me.sk145.gapples.Main
description: Craft god/notch apples
commands:
  gapples:
    usage: /<command> [craft]
    aliases: []
    description: Give yourself the items to craft a gapple.